### ISSUE TITLE
multiple clients key pairs 

### ISSUE THREAD

**Issue by Cryptohardy** [mimoo/NoiseGo#7]
I have integrated NoiseGo in my code using N_KK pattern . my next step is to distribute for every client a different key pair and I noticed that the code only works for single client. if I have to modify your code , where should I change to allow multiple clients with each key pair?

**Comment by mimoo** [comment]
I think you're mistaken because there is no N_KK pattern. Do you mean the [NK pattern](https://www.discocrypto.com/#/protocol/Noise_NK)? With this pattern the client does not have a keypair, so it should work for any number of clients. 

If it's the [KK pattern](https://www.discocrypto.com/#/protocol/Noise_K) then clients do have a key as well. But indeed I think the API is configured for a single client. It's easier to use the [XK pattern](https://noiseexplorer.com/patterns/XK/) if you're expecting several clients.

BTW there's a quizz on https://www.discocrypto.com/#/protocol/Overview that might be helpful to choose the correct pattern.

**Comment by Cryptohardy** [comment]
Thanks for the explanation , I meant Noise_KK , It is clear for me that IK or XK pattern are better options.
